services:
  app:
    build: .
    container_name: skp-warehouse-container
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - .:/var/www/html
    networks:
      - laravel-net
      - webproxy
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  nginx-internal:
    image: nginx:alpine
    container_name: nginx-skp-warehouse
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel-net
      - webproxy
    depends_on:
      - app

  db:
    image: mariadb:12
    container_name: db-skp-warehouse
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      MARIADB_DATABASE: ${DB_DATABASE}
      MARIADB_USER: ${DB_USERNAME}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD_ROOT}
    networks:
      - laravel-net
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost", "-u", "root", "-prootpassword"]
      interval: 10s
      timeout: 5s
      retries: 3

  redis:
    image: redis:alpine
    container_name: redis-skp-warehouse
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - laravel-net

networks:
  laravel-net:
  webproxy:
    external: true